name: Build Windows

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Windows x86_64
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          make
          mingw-w64-x86_64-gcc

    - name: Build Core (Software)
      run: |
        make -j$(nproc)
        mv mednafen_psx_libretro.dll mednafen_psx_libretro_sw.dll
        
    - name: Build Core (Hardware)
      run: |
        make clean
        make -j$(nproc) HAVE_HW=1
        mv mednafen_psx_libretro_sw.dll mednafen_psx_libretro.dll

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-x86_64-cores
        path: |
          mednafen_psx_libretro.dll
          mednafen_psx_hw_libretro.dll

